version: "3.8"

services:
  # PostgreSQL
  postgres:
    image: postgres:15
    container_name: itaipu_postgres
    environment:
      POSTGRES_DB: carrinho_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - itaipu_network

  # Projeto 1 - API de Moedas
  api-moedas:
    build:
      context: ./projeto-1-api-moedas
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: itaipu_api_moedas
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Dquarkus.http.host=0.0.0.0
    networks:
      - itaipu_network

  # Projeto 2 - Sistema de Carrinho
  system-cart:
    build:
      context: ./projeto-2-system-cart
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: itaipu_system_cart
    ports:
      - "8081:8081"
    environment:
      - JAVA_OPTS=-Dquarkus.http.host=0.0.0.0
      - QUARKUS_REST_CLIENT_CURRENCY_API_URL=http://api-moedas:8080
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres:5432/carrinho_db
      - QUARKUS_DATASOURCE_USERNAME=postgres
      - QUARKUS_DATASOURCE_PASSWORD=postgres
    depends_on:
      - api-moedas
      - postgres
    networks:
      - itaipu_network

volumes:
  postgres_data:

networks:
  itaipu_network:
    driver: bridge
